import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://subtitle-ai.vercel.app'
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/cs/',
          '/translate',
          '/cs/translate',
          '/subtitles-search',
          '/cs/subtitles-search',
          '/subtitle-editor',
          '/cs/subtitle-editor',
          '/video-tools',
          '/cs/video-tools',
          '/pricing',
          '/cs/pricing',
          '/about',
          '/cs/about',
          '/contact',
          '/cs/contact',
          '/privacy',
          '/cs/privacy',
          '/terms',
          '/cs/terms',
          '/cookies',
          '/cs/cookies',
          '/gdpr',
          '/cs/gdpr',
        ],
        disallow: [
          '/api/',
          '/dashboard',
          '/cs/dashboard',
          '/admin',
          '/(auth)/',
          '/(dashboard)/',
          '/debug*',
          '/test*',
          '/preview',
          '/cs/preview',
          '/success',
          '/verify-email',
          '/cs/verify-email',
          '/buy-credits',
          '/cs/buy-credits',
          '/batch',
          '/cs/batch',
          '/subtitle-popup',
          '/cs/subtitle-popup',
          '/my-feedback',
          '/cs/my-feedback',
          '/feedback',
          '/cs/feedback',
          '/cookie-settings',
          '/cs/cookie-settings',
          // Old/incorrect URLs (now redirected)
          '/video-player',
          '/subtitle-overlay',
          '/help',
          '/privacy-policy',
          '/cookie-policy',
          '/faq',
          '/support',
          '/$',
        ],
      },
      // Special rules for AI crawlers
      {
        userAgent: 'GPTBot',
        allow: [
          '/',
          '/cs/',
          '/translate',
          '/cs/translate',
          '/subtitles-search',
          '/cs/subtitles-search',
          '/subtitle-editor',
          '/cs/subtitle-editor',
          '/video-tools',
          '/cs/video-tools',
          '/pricing',
          '/cs/pricing',
          '/about',
          '/cs/about',
        ],
        disallow: [
          '/api/',
          '/dashboard',
          '/admin',
          '/debug*',
          '/test*',
        ],
      },
      {
        userAgent: 'ChatGPT-User',
        allow: [
          '/',
          '/cs/',
          '/translate',
          '/cs/translate',
          '/subtitles-search',
          '/cs/subtitles-search',
          '/subtitle-editor',
          '/cs/subtitle-editor',
          '/video-tools',
          '/cs/video-tools',
          '/pricing',
          '/cs/pricing',
          '/about',
          '/cs/about',
        ],
        disallow: [
          '/api/',
          '/dashboard',
          '/admin',
          '/debug*',
          '/test*',
        ],
      },
      {
        userAgent: 'Claude-Web',
        allow: [
          '/',
          '/cs/',
          '/translate',
          '/cs/translate',
          '/subtitles-search',
          '/cs/subtitles-search',
          '/subtitle-editor',
          '/cs/subtitle-editor',
          '/video-tools',
          '/cs/video-tools',
          '/pricing',
          '/cs/pricing',
          '/about',
          '/cs/about',
        ],
        disallow: [
          '/api/',
          '/dashboard',
          '/admin',
          '/debug*',
          '/test*',
        ],
      },
      {
        userAgent: 'PerplexityBot',
        allow: [
          '/',
          '/cs/',
          '/translate',
          '/cs/translate',
          '/subtitles-search',
          '/cs/subtitles-search',
          '/subtitle-editor',
          '/cs/subtitle-editor',
          '/video-tools',
          '/cs/video-tools',
          '/pricing',
          '/cs/pricing',
          '/about',
          '/cs/about',
        ],
        disallow: [
          '/api/',
          '/dashboard',
          '/admin',
          '/debug*',
          '/test*',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  }
}
