export type ToolLocale = 'en' | 'cs'
export type ToolMode = 'sync' | 'validator' | 'reading-speed' | 'converter' | 'encoding'

export interface ToolDefinition {
  slug: string
  mode: ToolMode
  locale: ToolLocale
  title: string
  description: string
  shortDescription: string
  steps: string[]
  faq: Array<{ question: string; answer: string }>
}

const en: ToolDefinition[] = [
  { slug: 'subtitle-sync', mode: 'sync', locale: 'en', title: 'Subtitle Sync and FPS Converter', shortDescription: 'Shift every cue or rescale timing between 23.976, 24 and 25 FPS.', description: 'Fix SRT and WebVTT subtitles that appear early, late, or gradually drift. Processing stays in your browser.', steps: ['Load or paste an SRT or VTT file.', 'Enter a positive or negative offset and, if needed, source and target FPS.', 'Preview the first cues and download the corrected file.'], faq: [{ question: 'Is my subtitle uploaded?', answer: 'No. Parsing, timing conversion, preview, and download run locally in your browser.' }, { question: 'What offset fixes early subtitles?', answer: 'Use a positive offset to move early subtitles later.' }, { question: 'Can I combine FPS conversion and offset?', answer: 'Yes. FPS scaling is applied first, followed by the constant offset.' }] },
  { slug: 'srt-validator', mode: 'validator', locale: 'en', title: 'SRT and VTT Subtitle Validator', shortDescription: 'Find invalid timestamps, empty cues, overlaps, and ordering problems.', description: 'Validate subtitle structure before translation, publishing, or playback. The tool reports errors and warnings without uploading the file.', steps: ['Load or paste the subtitle.', 'Review structural errors and timing warnings.', 'Correct the source and validate it again.'], faq: [{ question: 'What does the validator check?', answer: 'It checks timestamp syntax, cue duration, empty text, chronological order, and overlaps.' }, { question: 'Are overlaps always wrong?', answer: 'Not always. They can be intentional for multiple speakers or positioned subtitles, so they are warnings.' }, { question: 'Does validation change the file?', answer: 'No. The validator only reads and reports.' }] },
  { slug: 'subtitle-reading-speed', mode: 'reading-speed', locale: 'en', title: 'Subtitle Reading Speed Analyzer', shortDescription: 'Measure characters per second, line length, and cue duration.', description: 'Identify subtitle cues that may be too fast or too long to read comfortably, with configurable CPS and line-length thresholds.', steps: ['Load an SRT or VTT file.', 'Set the maximum characters-per-second and line-length thresholds.', 'Review flagged cues and edit them in context.'], faq: [{ question: 'What is CPS?', answer: 'Characters per second divides visible characters by the cue display duration.' }, { question: 'Is one CPS limit correct for every audience?', answer: 'No. Language, age, accessibility needs, and platform guidelines can require different thresholds.' }, { question: 'Does markup count?', answer: 'Basic HTML and ASS-style tags are removed before character counting.' }] },
  { slug: 'subtitle-format-converter', mode: 'converter', locale: 'en', title: 'SRT to VTT and VTT to SRT Converter', shortDescription: 'Convert subtitle timing syntax and structure in your browser.', description: 'Convert common SRT and WebVTT subtitle files locally. Dialogue and timing are preserved; unsupported advanced settings may be removed.', steps: ['Load or paste SRT or WebVTT.', 'Choose the output format.', 'Preview and download the converted file.'], faq: [{ question: 'What changes during conversion?', answer: 'Timestamp punctuation, headers, cue numbering, and supported cue settings are adapted.' }, { question: 'Can it convert ASS?', answer: 'This focused converter supports SRT and VTT. ASS styling requires a more specialized conversion.' }, { question: 'Will styling be preserved?', answer: 'Only simple text markup common to both formats. Format-specific positioning can be lost.' }] },
  { slug: 'subtitle-encoding-detector', mode: 'encoding', locale: 'en', title: 'Subtitle Encoding Detector and UTF-8 Converter', shortDescription: 'Detect BOMs, validate UTF-8, preview text, and export UTF-8.', description: 'Diagnose broken accents and unreadable subtitle characters. Detection and UTF-8 conversion happen locally in your browser.', steps: ['Choose a subtitle file.', 'Review the detected encoding and decoded preview.', 'Download a normalized UTF-8 copy if required.'], faq: [{ question: 'Why do I see boxes or question marks?', answer: 'The player may be decoding the file with a different character encoding than the one used to save it.' }, { question: 'Is encoding detection always certain?', answer: 'BOM and valid UTF-8 detection are strong. Distinguishing similar legacy single-byte encodings is heuristic.' }, { question: 'Is UTF-8 safe for modern players?', answer: 'Yes. UTF-8 is the most portable modern choice for multilingual subtitle text.' }] },
]

const csText: Record<ToolMode, Omit<ToolDefinition, 'slug' | 'mode' | 'locale'>> = {
  sync: { title: 'Synchronizace titulků a převod FPS', shortDescription: 'Posuňte všechny cue nebo převeďte časování mezi 23,976, 24 a 25 FPS.', description: 'Opravte SRT a WebVTT titulky, které se zobrazují brzy, pozdě nebo se postupně rozcházejí. Soubor zůstává v prohlížeči.', steps: ['Načtěte nebo vložte SRT či VTT.', 'Zadejte kladný nebo záporný posun a případně zdrojové a cílové FPS.', 'Zkontrolujte náhled a stáhněte opravený soubor.'], faq: [{ question: 'Nahrává se soubor na server?', answer: 'Ne. Zpracování probíhá lokálně v prohlížeči.' }, { question: 'Jaký posun opraví příliš časné titulky?', answer: 'Použijte kladnou hodnotu, která titulky posune později.' }, { question: 'Lze spojit FPS a posun?', answer: 'Ano. Nejdřív se přepočítá FPS a potom přidá konstantní posun.' }] },
  validator: { title: 'Validátor SRT a VTT titulků', shortDescription: 'Najděte chybné časy, prázdné cue, překryvy a pořadí.', description: 'Zkontrolujte strukturu titulků před překladem, publikací nebo přehráním, aniž by se soubor nahrával.', steps: ['Načtěte nebo vložte titulky.', 'Projděte chyby a varování.', 'Opravte zdroj a validaci zopakujte.'], faq: [{ question: 'Co validátor kontroluje?', answer: 'Syntax času, délku cue, prázdný text, pořadí a překryvy.' }, { question: 'Je překryv vždy chyba?', answer: 'Ne. Může být záměrný, proto je veden jako varování.' }, { question: 'Mění validátor soubor?', answer: 'Ne, pouze jej čte.' }] },
  'reading-speed': { title: 'Analýza rychlosti čtení titulků', shortDescription: 'Změřte znaky za sekundu, délku řádku a dobu zobrazení.', description: 'Najděte cue, které mohou být příliš rychlé nebo dlouhé, a nastavte vlastní limity CPS a délky řádku.', steps: ['Načtěte SRT nebo VTT.', 'Nastavte limity.', 'Zkontrolujte označené cue.'], faq: [{ question: 'Co je CPS?', answer: 'Počet viditelných znaků dělený dobou zobrazení cue.' }, { question: 'Je jeden limit vhodný pro všechny?', answer: 'Ne. Liší se podle jazyka, publika a platformy.' }, { question: 'Počítají se značky?', answer: 'Základní HTML a ASS značky se před výpočtem odstraní.' }] },
  converter: { title: 'Převodník SRT na VTT a VTT na SRT', shortDescription: 'Převeďte syntax času a strukturu přímo v prohlížeči.', description: 'Lokální převod mezi SRT a WebVTT. Dialog a čas se zachovají; nepodporované pokročilé nastavení může být odstraněno.', steps: ['Načtěte nebo vložte soubor.', 'Vyberte výstupní formát.', 'Zkontrolujte a stáhněte výsledek.'], faq: [{ question: 'Co se při převodu mění?', answer: 'Interpunkce času, hlavička, číslování cue a podporovaná nastavení.' }, { question: 'Umí převod ASS?', answer: 'Tento nástroj je zaměřen na SRT a VTT.' }, { question: 'Zachovají se styly?', answer: 'Jen jednoduché značky společné oběma formátům.' }] },
  encoding: { title: 'Detekce kódování titulků a převod do UTF-8', shortDescription: 'Najděte BOM, ověřte UTF-8, zobrazte text a exportujte UTF-8.', description: 'Diagnostikujte rozbitou diakritiku a nečitelné znaky. Detekce i převod probíhají lokálně.', steps: ['Vyberte subtitle soubor.', 'Prohlédněte detekované kódování a náhled.', 'V případě potřeby stáhněte UTF-8 verzi.'], faq: [{ question: 'Proč vidím čtverečky nebo otazníky?', answer: 'Přehrávač pravděpodobně používá jiné kódování než soubor.' }, { question: 'Je detekce vždy jistá?', answer: 'BOM a UTF-8 jsou spolehlivé; rozlišení podobných starších kódování je odhad.' }, { question: 'Je UTF-8 vhodné pro moderní přehrávače?', answer: 'Ano, je nejpřenosnější volbou pro vícejazyčný text.' }] },
}

export const tools: ToolDefinition[] = [...en, ...en.map((tool) => ({ ...tool, ...csText[tool.mode], locale: 'cs' as const }))]
export function getTools(locale: ToolLocale) { return tools.filter((tool) => tool.locale === locale) }
export function getTool(slug: string, locale: ToolLocale) { return tools.find((tool) => tool.slug === slug && tool.locale === locale) }
